"use client";

import { useEffect, useMemo, useState } from "react";
import { ethers } from "ethers";

type Wallet = { id:string; label:string; address:string; chainId:number };
type Collection = { id:string; name:string; contractAddress:string; chainId:number; mintPrice:string|null; maxPerWallet:number|null; maxSupply:number|null; currentSupply:number|null; phaseStatus:string; startsAt:string|null; endsAt:string|null; createdAt:string };
type Job = { id:string; walletId:string; collectionId:string; status:string; quantity:number; scheduledAt:string|null; createdAt:string; error?:string|null };

const short = (v:string) => `${v.slice(0,6)}…${v.slice(-5)}`;

export default function MintsPage() {
  const [query,setQuery]=useState(""); const [wallets,setWallets]=useState<Wallet[]>([]); const [collections,setCollections]=useState<Collection[]>([]); const [jobs,setJobs]=useState<Job[]>([]);
  const [project,setProject]=useState<Collection|null>(null); const [selected,setSelected]=useState<Set<string>>(new Set()); const [qty,setQty]=useState(1);
  const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const [expanded,setExpanded]=useState<string|null>(null); const [tab,setTab]=useState("minted");
  const load=()=>Promise.all([fetch("/api/wallets").then(r=>r.json()),fetch("/api/collections").then(r=>r.json()),fetch("/api/jobs?limit=100").then(r=>r.json())]).then(([w,c,j])=>{setWallets(Array.isArray(w)?w:[]);setCollections(Array.isArray(c)?c:[]);setJobs(Array.isArray(j)?j:[])}).catch(()=>{});
  useEffect(()=>{load()},[]);
  const compatible=useMemo(()=>project?wallets.filter(w=>w.chainId===project.chainId):wallets,[wallets,project]);
  const resolve=async()=>{setBusy(true);setMessage("Scanning supported mint adapters…");try{const response=await fetch("/api/mints/resolve",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({input:query})});const data=await response.json();if(!response.ok||!data.supported)throw new Error(data.reason||"This mint isn’t supported yet");const phase=data.phases?.find((item:{status:string})=>item.status==="live")||data.phases?.[0];setProject({id:data.collectionId,name:data.name,contractAddress:data.contractAddress,chainId:data.chainId,mintPrice:phase?.priceWei||null,maxPerWallet:phase?.maxPerWallet||null,maxSupply:data.maxSupply||null,currentSupply:data.currentSupply??null,phaseStatus:phase?.status||"unknown",startsAt:phase?.startsAt||null,endsAt:phase?.endsAt||null,createdAt:""});setMessage("");setSelected(new Set())}catch(error){setProject(null);setMessage(error instanceof Error?error.message:"This mint isn’t supported yet")}finally{setBusy(false)}};
  const toggle=(id:string)=>setSelected(p=>{const n=new Set(p);if(n.has(id))n.delete(id);else n.add(id);return n});
  const schedule=async()=>{if(!project||!selected.size)return;setBusy(true);setMessage("");try{const idempotencyKey=crypto.randomUUID();const contractStart=project.startsAt&&Date.parse(project.startsAt)>Date.now()?project.startsAt:undefined;const r=await fetch("/api/jobs/batch",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":idempotencyKey},body:JSON.stringify({collectionId:project.id,walletIds:[...selected],quantity:qty,scheduledAt:contractStart})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage(`${selected.size} mint task${selected.size>1?"s":""} scheduled ${contractStart?"for the contract opening time":"to run now"}.`);await load()}catch(e){setMessage(e instanceof Error?e.message:"Could not schedule mint")}finally{setBusy(false)}};
  const formatPrice=(wei:string|null)=>wei?`${ethers.formatEther(wei)} ETH`:"FREE";
  const formatContractTime=(value:string|null)=>value?new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"medium",timeZoneName:"short"}).format(new Date(value)):"Runs immediately (mint is live)";
  const groups=useMemo(()=>{const map=new Map<string,Job[]>();jobs.forEach(j=>map.set(j.collectionId,[...(map.get(j.collectionId)||[]),j]));return [...map.entries()]},[jobs]);
  return <>
    <div className="page-heading"><div><h1>Mints</h1><p>Paste a supported mint link and we&apos;ll handle the rest.</p></div></div>
    <div className="search-box"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&resolve()} placeholder="Paste mint URL, contract, or project name"/><button disabled={busy} onClick={resolve}>{busy?"Checking…":"Find mint →"}</button></div>
    {message&&<div className="alert" style={{marginBottom:18}}>{message}</div>}
    {!project?<div className="panel empty"><div><svg width="56" height="56" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3"><path d="M20 4c-8 0-14 3.5-14 10 0 3 2 5 5 5 6.5 0 9-7 9-15Z"/><path d="M4 21c2-5 6-8 11-11"/></svg><h2>No mint selected</h2><p>Supported and scheduled mints will appear here.</p></div></div>:
    <section className="panel mint-card">
      <div className="mint-hero"><div className="mint-identity"><div className="project-art">◈</div><div className="mint-title"><h2>{project.name}</h2><p>{short(project.contractAddress)} · Chain {project.chainId}</p></div></div><div className="supply"><b>{project.maxSupply?`${(project.currentSupply||0).toLocaleString()} / ${project.maxSupply.toLocaleString()}`:"Live mint"}</b><span>On-chain supply</span><div className="progress"><i style={{width:project.maxSupply?`${Math.min(100,((project.currentSupply||0)/project.maxSupply)*100)}%`:"0%"}}/></div></div></div>
      <div className="mint-body"><div className="mint-grid"><div className="phase-list"><div className="phase"><div className="phase-top"><h3>PUBLIC</h3><span className="status">{project.phaseStatus==="upcoming"?"Upcoming":"Supported"}</span></div><div className="chip-row"><span className="chip">PRICE · <strong>{formatPrice(project.mintPrice)}</strong></span><span className="chip">MAX · <strong>{project.maxPerWallet||"—"}</strong></span><span className="chip">ELIGIBLE · <strong>{compatible.length}</strong></span></div></div><div className="phase"><div className="phase-top"><h3>Mint configuration</h3><span className="muted" style={{fontSize:12}}>Automatic gas</span></div><div className="field" style={{marginTop:12}}><label>Quantity per wallet</label><div className="amount-row"><input type="number" min="1" max={project.maxPerWallet||100} value={qty} onChange={e=>setQty(Math.min(project.maxPerWallet||100,Math.max(1,Number(e.target.value))))}/><button className="secondary-btn" onClick={()=>setQty(project.maxPerWallet||1)}>Max</button></div></div></div></div>
        <div className="schedule-box"><div className="field"><label>Wallets ({selected.size} selected)</label><div className="wallet-picker">{compatible.length?compatible.map(w=><label className="wallet-option" key={w.id}><input type="checkbox" checked={selected.has(w.id)} onChange={()=>toggle(w.id)}/><span>{w.label}</span><small>{short(w.address)}</small></label>):<div className="wallet-option muted">No compatible wallets</div>}</div></div><div className="field"><label>Contract schedule</label><div className="alert">{project.phaseStatus==="upcoming"&&project.startsAt?`Automatically scheduled for ${formatContractTime(project.startsAt)}`:formatContractTime(null)}</div></div><button className="primary-btn" disabled={!selected.size||busy} onClick={schedule}>{busy?"Scheduling…":"Schedule mint →"}</button><div className="alert">Transactions are simulated before broadcast. Gas and nonce are handled automatically.</div></div>
      </div></div>
    </section>}
    {groups.length>0&&<section className="scheduled"><div className="section-title"><h2>Scheduled & recent</h2><span className="muted" style={{fontSize:12}}>{jobs.length} tasks</span></div>{groups.map(([cid,items])=>{const c=collections.find(x=>x.id===cid);const id=cid;const success=items.filter(x=>x.status==="completed").length;return <div className="panel job" key={id}><div className="job-summary" onClick={()=>setExpanded(expanded===id?null:id)}><div className="job-art"/><div className="job-main"><b>{c?.name||"Supported mint"}</b><span>{items.length} wallets · {items.reduce((a,b)=>a+b.quantity,0)} total · {success} hits</span></div><span className="status">{items.some(x=>x.status==="running")?"Running":items.some(x=>x.status==="pending")?"Scheduled":"Finished"}</span><span>{expanded===id?"⌃":"⌄"}</span></div>{expanded===id&&<div className="result-panel"><div className="result-tabs">{["minted","transactions","analytics"].map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>{tab==="analytics"?<div className="summary-box"><div className="summary-line"><span>Total tasks</span><b>{items.length}</b></div><div className="summary-line"><span>Successful hits</span><b className="ok">{success}</b></div><div className="summary-line"><span>Failed</span><b className="failed">{items.filter(x=>x.status==="failed").length}</b></div><div className="summary-line"><span>Hit rate</span><b>{items.length?Math.round(success/items.length*100):0}%</b></div></div>:<table className="result-table"><thead><tr><th>Status</th><th>{tab==="minted"?"Wallet":"Task"}</th><th>Amount</th><th>Result</th></tr></thead><tbody>{items.map(j=>{const w=wallets.find(x=>x.id===j.walletId);return <tr key={j.id}><td className={j.status==="failed"?"failed":"ok"}>{j.status==="failed"?"✕":"✓"}</td><td className="mono">{tab==="minted"?short(w?.address||j.walletId):short(j.id)}</td><td>{j.quantity}</td><td>{j.error||j.status}</td></tr>})}</tbody></table>}</div>}</div>})}</section>}
  </>;
}
