"use client";
import { useEffect,useMemo,useState } from "react";
import { ethers } from "ethers";
type Wallet={id:string;label:string;address:string;chainId:number;role:"main"|"worker";parentWalletId:string|null;active:boolean};
type Preview={version:2;type:"fund"|"sweep";mainWalletId:string;workerWalletIds:string[];chainId:number;transfers:Array<{fromWalletId:string;toWalletId:string;amountWei:string;gasLimit:string;maxFeePerGas:string;maxPriorityFeePerGas:string|null}>;estimatedGasWei:string;totalRequiredWei:string;generatedAt:string;expiresAt:string;fingerprint:string};
export default function DispersePage(){
 const [wallets,setWallets]=useState<Wallet[]>([]),[main,setMain]=useState(""),[selected,setSelected]=useState<Set<string>>(new Set()),[amount,setAmount]=useState(""),[type,setType]=useState<"fund"|"sweep">("fund"),[message,setMessage]=useState(""),[preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch("/api/wallets").then(r=>r.json()).then(d=>setWallets(Array.isArray(d)?d:[])).catch(()=>{})},[]);
 const mains=wallets.filter(w=>w.role==="main"&&w.active),workers=useMemo(()=>wallets.filter(w=>w.role==="worker"&&w.active&&w.parentWalletId===main),[wallets,main]);
 const toggle=(id:string)=>setSelected(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);setPreview(null);return next});
 const requestPreview=async()=>{setBusy(true);setMessage("");try{const response=await fetch("/api/disperse",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"preview",type,mainWalletId:main,workerWalletIds:[...selected],amountPerWallet:type==="fund"?amount:undefined})});const data=await response.json();if(!response.ok)throw new Error(data.error);setPreview(data)}catch(error){setPreview(null);setMessage(error instanceof Error?error.message:"Could not preview") }finally{setBusy(false)}};
 const execute=async()=>{if(!preview)return;setBusy(true);try{const response=await fetch("/api/disperse",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({action:"execute",type,mainWalletId:main,workerWalletIds:[...selected],amountPerWallet:type==="fund"?amount:undefined,expected:preview})});const data=await response.json();if(!response.ok)throw new Error(data.error);setMessage(`Operation queued safely: ${data.operationId}. It will wait if broadcasting is locked.`);setPreview(null)}catch(error){setMessage(error instanceof Error?error.message:"Could not execute")}finally{setBusy(false)}};
 return <><div className="page-heading"><div><h1>Disperse</h1><p>Fund workers from main, or sweep balances back.</p></div></div><div className="panel disperse-grid"><div className="form-grid"><div className="segmented"><button className={type==="fund"?"active":""} onClick={()=>{setType("fund");setPreview(null)}}>Fund workers</button><button className={type==="sweep"?"active":""} onClick={()=>{setType("sweep");setPreview(null)}}>Sweep to main</button></div><div className="field"><label>Main wallet</label><select value={main} onChange={e=>{setMain(e.target.value);setSelected(new Set());setPreview(null)}}><option value="">Choose main wallet</option>{mains.map(w=><option key={w.id} value={w.id}>{w.label}</option>)}</select></div><div className="field"><label>Workers ({selected.size} selected)</label><div className="wallet-picker">{workers.length?workers.map(w=><label className="wallet-option" key={w.id}><input type="checkbox" checked={selected.has(w.id)} onChange={()=>toggle(w.id)}/><span>{w.label}</span><small>{w.address.slice(0,7)}…{w.address.slice(-5)}</small></label>):<div className="wallet-option muted">Choose a main wallet with workers</div>}</div></div>{type==="fund"&&<div className="field"><label>Amount per worker</label><input value={amount} onChange={e=>{setAmount(e.target.value);setPreview(null)}} inputMode="decimal" placeholder="0.01"/></div>}</div><div className="form-grid"><div className="summary-box"><div className="summary-line"><span>Direction</span><b>{type==="fund"?"Main → workers":"Workers → main"}</b></div><div className="summary-line"><span>Workers</span><b>{selected.size}</b></div><div className="summary-line"><span>Transfers</span><b>{preview?.transfers.length||0}</b></div><div className="summary-line"><span>{type==="fund"?"Total required":"Estimated return"}</span><b>{preview?ethers.formatEther(preview.totalRequiredWei):"—"}</b></div><div className="summary-line"><span>Estimated network fee</span><b>{preview?ethers.formatEther(preview.estimatedGasWei):"—"}</b></div></div>{message&&<div className="alert">{message}</div>}{!preview?<button className="primary-btn" disabled={busy||!main||!selected.size||(type==="fund"&&!amount)} onClick={requestPreview}>{busy?"Checking balances & fees…":"Review disperse →"}</button>:<><div className="alert">Balances and current network fees were checked. Re-preview is required if anything changes.</div><button className="primary-btn" disabled={busy} onClick={execute}>{busy?"Submitting…":type==="fund"?"Fund workers":"Sweep to main"}</button></>}</div></div></>;
}
