"use client";
import { useEffect,useState } from "react";

type Wallet={id:string;label:string;address:string;chainId:number;keyFormat:string;active:boolean;role:"main"|"worker";parentWalletId:string|null};
type BackupWallet={label:string;address:string;privateKey:string};
type Chain={id:number;name:string;symbol:string};
type WalletEdit={id:string;label:string;active:boolean;keyType:"private-key"|"mnemonic";key:string;hdPath:string;adminPassword:string};
const short=(v:string)=>`${v.slice(0,7)}…${v.slice(-5)}`;

export default function WalletsPage(){
 const [wallets,setWallets]=useState<Wallet[]>([]),[chains,setChains]=useState<Chain[]>([]),[loading,setLoading]=useState(true),[modal,setModal]=useState(false),[generateModal,setGenerateModal]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[backup,setBackup]=useState<BackupWallet[]>([]);
 const [edit,setEdit]=useState<WalletEdit|null>(null),[deleteId,setDeleteId]=useState<string|null>(null),[adminPassword,setAdminPassword]=useState("");
 const [form,setForm]=useState({label:"",chainId:1,keyType:"private-key",key:"",role:"main" as "main"|"worker",parentWalletId:""});
 const [generate,setGenerate]=useState({prefix:"Worker",chainId:1,count:10,parentWalletId:""});
 const load=()=>Promise.all([fetch("/api/wallets").then(r=>r.json()),fetch("/api/chains").then(r=>r.json())]).then(([w,c])=>{setWallets(Array.isArray(w)?w:[]);setChains(Array.isArray(c)?c:[]);setLoading(false)});
 useEffect(()=>{load()},[]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/wallets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,parentWalletId:form.role==="worker"?form.parentWalletId:undefined})});const d=await r.json();if(!r.ok)throw new Error(d.error);setModal(false);setForm({label:"",chainId:1,keyType:"private-key",key:"",role:"main",parentWalletId:""});load()}catch(e){setError(e instanceof Error?e.message:"Import failed")}finally{setBusy(false)}};
 const createWallets=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/wallets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"generate",...generate})});const d=await r.json();if(!r.ok)throw new Error(d.error);setBackup(d.wallets);setGenerateModal(false);load()}catch(e){setError(e instanceof Error?e.message:"Generation failed")}finally{setBusy(false)}};
 const mainWallets=wallets.filter(w=>w.role==="main");
 const downloadBackup=()=>{const blob=new Blob([JSON.stringify(backup,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`mintbot-wallet-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)};
 const closeImport=()=>{setModal(false);setForm(current=>({...current,key:""}))};
 const saveEdit=async(e:React.FormEvent)=>{e.preventDefault();if(!edit)return;setBusy(true);setError("");try{const replacement=edit.key.trim()?{keyType:edit.keyType,key:edit.key,hdPath:edit.keyType==="mnemonic"?edit.hdPath||undefined:undefined}:undefined;const response=await fetch(`/api/wallets/${edit.id}`,{method:"PATCH",headers:{"Content-Type":"application/json",...(replacement?{"X-Admin-Password":edit.adminPassword}:{})},body:JSON.stringify({label:edit.label,active:edit.active,replacement})});const data=await response.json();if(!response.ok)throw new Error(data.error);setEdit(null);await load()}catch(error){setError(error instanceof Error?error.message:"Could not update wallet")}finally{setBusy(false)}};
 const remove=async()=>{if(!deleteId)return;setBusy(true);setError("");try{const response=await fetch(`/api/wallets/${deleteId}`,{method:"DELETE",headers:{"X-Admin-Password":adminPassword}});const data=await response.json();if(!response.ok)throw new Error(data.error);setDeleteId(null);setAdminPassword("");await load()}catch(error){setError(error instanceof Error?error.message:"Could not remove wallet")}finally{setBusy(false)}};
 return <><div className="page-heading"><div><h1>Wallets</h1><p>Create multiple main wallets per network and organise workers beneath the correct main.</p></div><div className="toolbar"><button className="secondary-btn" onClick={()=>navigator.clipboard.writeText(wallets.map(w=>w.address).join("\n"))}>Copy addresses</button><button className="secondary-btn" onClick={()=>{setError("");setModal(true)}}>Import wallet</button><button className="primary-btn" onClick={()=>{setError("");setGenerateModal(true)}}>+ Create workers</button></div></div>
 <div className="panel table-wrap">{loading?<div className="empty"><p>Loading wallets…</p></div>:wallets.length?<table className="wallet-table"><thead><tr><th>Name</th><th>Address</th><th>Network</th><th>Role</th><th></th></tr></thead><tbody>{wallets.map(w=><tr key={w.id}><td><b>{w.role==="worker"?"↳ ":""}{w.label}</b>{!w.active&&<span className="muted"> · inactive</span>}</td><td className="mono">{short(w.address)} <button className="icon-button" style={{width:28,height:28,fontSize:12,marginLeft:6}} onClick={()=>navigator.clipboard.writeText(w.address)}>⧉</button></td><td>{chains.find(c=>c.id===w.chainId)?.name||`Chain ${w.chainId}`}</td><td className="muted">{w.role==="main"?"Main wallet":"Worker"}</td><td><div className="toolbar"><button className="secondary-btn" style={{padding:"6px 9px"}} onClick={()=>{setError("");setEdit({id:w.id,label:w.label,active:w.active,keyType:"private-key",key:"",hdPath:"",adminPassword:""})}}>Edit</button><button className="secondary-btn" style={{padding:"6px 9px",color:"var(--danger)"}} onClick={()=>{setError("");setDeleteId(w.id);setAdminPassword("")}}>Remove</button></div></td></tr>)}</tbody></table>:<div className="empty"><div><h2>No wallets yet</h2><p>Import your main wallet first, then create workers under it.</p><button className="primary-btn" style={{marginTop:18}} onClick={()=>setModal(true)}>Import main wallet</button></div></div>}</div>
 {modal&&<div className="modal-backdrop" onMouseDown={closeImport}><form className="panel modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>Import wallet</h2><p className="muted" style={{fontSize:12,margin:"5px 0 0"}}>Keys are encrypted before storage. Each network may have multiple independent main wallets.</p></div><button type="button" onClick={closeImport}>×</button></div>{error&&<div className="alert" style={{color:"var(--danger)",marginBottom:14}}>{error}</div>}<div className="form-grid"><div className="segmented"><button type="button" className={form.role==="main"?"active":""} onClick={()=>setForm({...form,role:"main",parentWalletId:""})}>Main wallet</button><button type="button" className={form.role==="worker"?"active":""} onClick={()=>setForm({...form,role:"worker"})}>Worker</button></div><div className="segmented"><button type="button" className={form.keyType==="private-key"?"active":""} onClick={()=>setForm({...form,keyType:"private-key"})}>Private key</button><button type="button" className={form.keyType==="mnemonic"?"active":""} onClick={()=>setForm({...form,keyType:"mnemonic"})}>Seed phrase</button></div><div className="field"><label>Wallet name</label><input required value={form.label} onChange={e=>setForm({...form,label:e.target.value})} placeholder={form.role==="main"?"Main 02":"Worker 01"}/></div><div className="field"><label>Network</label><select value={form.chainId} onChange={e=>setForm({...form,chainId:Number(e.target.value),parentWalletId:""})}>{chains.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>{form.role==="worker"&&<div className="field"><label>Parent main wallet</label><select required value={form.parentWalletId} onChange={e=>setForm({...form,parentWalletId:e.target.value})}><option value="">Choose main</option>{mainWallets.filter(w=>w.chainId===form.chainId&&w.active).map(w=><option key={w.id} value={w.id}>{w.label} · {short(w.address)}</option>)}</select></div>}<div className="field"><label>{form.keyType==="mnemonic"?"Seed phrase":"Private key"}</label><textarea required rows={3} value={form.key} onChange={e=>setForm({...form,key:e.target.value})} placeholder={form.keyType==="mnemonic"?"Enter 12–24 words":"0x…"}/></div><button className="primary-btn" disabled={busy}>{busy?"Encrypting & importing…":"Import wallet"}</button></div></form></div>}
 {generateModal&&<div className="modal-backdrop" onMouseDown={()=>setGenerateModal(false)}><form className="panel modal" onSubmit={createWallets} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>Create worker wallets</h2><p className="muted" style={{fontSize:12,margin:"5px 0 0"}}>Independent keys, grouped beneath the selected main wallet.</p></div><button type="button" onClick={()=>setGenerateModal(false)}>×</button></div>{error&&<div className="alert" style={{color:"var(--danger)",marginBottom:14}}>{error}</div>}<div className="form-grid"><div className="field"><label>Parent main wallet</label><select required value={generate.parentWalletId} onChange={e=>{const main=mainWallets.find(w=>w.id===e.target.value);setGenerate({...generate,parentWalletId:e.target.value,chainId:main?.chainId||generate.chainId})}}><option value="">Choose main</option>{mainWallets.filter(w=>w.active).map(w=><option key={w.id} value={w.id}>{w.label} · {chains.find(c=>c.id===w.chainId)?.name||`Chain ${w.chainId}`} · {short(w.address)}</option>)}</select></div><div className="field"><label>Name prefix</label><input required value={generate.prefix} onChange={e=>setGenerate({...generate,prefix:e.target.value})} placeholder="Worker"/></div><div className="field"><label>Count (maximum 100)</label><div className="amount-row"><input type="number" min="1" max="100" value={generate.count} onChange={e=>setGenerate({...generate,count:Math.max(1,Math.min(100,Number(e.target.value)||1))})}/><button type="button" className="secondary-btn" onClick={()=>setGenerate({...generate,count:100})}>MAX</button></div></div><div className="alert">Private keys are shown once after creation. Back them up before funding.</div><button className="primary-btn" disabled={busy||!generate.parentWalletId}>{busy?`Creating ${generate.count}…`:`Create ${generate.count} worker${generate.count===1?"":"s"}`}</button></div></form></div>}
 {edit&&<div className="modal-backdrop" onMouseDown={()=>setEdit(null)}><form className="panel modal" onSubmit={saveEdit} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>Edit wallet</h2><p className="muted" style={{fontSize:12,margin:"5px 0 0"}}>Labels and status are safe edits. Replacing the address requires its matching signing key.</p></div><button type="button" onClick={()=>setEdit(null)}>×</button></div>{error&&<div className="alert" style={{color:"var(--danger)",marginBottom:14}}>{error}</div>}<div className="form-grid"><div className="field"><label>Wallet name</label><input required value={edit.label} onChange={e=>setEdit({...edit,label:e.target.value})}/></div><label className="wallet-option"><input type="checkbox" checked={edit.active} onChange={e=>setEdit({...edit,active:e.target.checked})}/><span>Active</span></label><div className="alert">To change the address, replace the encrypted signing key below. Leave blank to keep the current address.</div><div className="segmented"><button type="button" className={edit.keyType==="private-key"?"active":""} onClick={()=>setEdit({...edit,keyType:"private-key"})}>Private key</button><button type="button" className={edit.keyType==="mnemonic"?"active":""} onClick={()=>setEdit({...edit,keyType:"mnemonic"})}>Seed phrase</button></div><div className="field"><label>Replacement {edit.keyType==="mnemonic"?"seed phrase":"private key"} (optional)</label><textarea rows={3} value={edit.key} onChange={e=>setEdit({...edit,key:e.target.value})} placeholder="Leave blank to keep current signing key"/></div>{edit.key.trim()&&<><div className="field"><label>Admin password</label><input type="password" required autoComplete="current-password" value={edit.adminPassword} onChange={e=>setEdit({...edit,adminPassword:e.target.value})}/></div><div className="alert" style={{color:"var(--danger)"}}>The address is derived from this key. Confirm any funded old address is backed up before replacement.</div></>}<button className="primary-btn" disabled={busy}>{busy?"Saving…":"Save wallet"}</button></div></form></div>}
 {deleteId&&<div className="modal-backdrop" onMouseDown={()=>setDeleteId(null)}><form className="panel modal" onSubmit={e=>{e.preventDefault();void remove()}} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>Remove wallet</h2><p className="muted" style={{fontSize:12,margin:"5px 0 0"}}>This requires fresh administrator approval.</p></div><button type="button" onClick={()=>setDeleteId(null)}>×</button></div>{error&&<div className="alert" style={{color:"var(--danger)",marginBottom:14}}>{error}</div>}<div className="form-grid"><div className="field"><label>Admin password</label><input type="password" required autoFocus autoComplete="current-password" placeholder="App login password" value={adminPassword} onChange={e=>setAdminPassword(e.target.value)}/></div><div className="alert">Wallets with transaction history are deactivated instead of erased so recovery and audit records remain intact.</div><button className="primary-btn" style={{background:"var(--danger)"}} disabled={busy||!adminPassword}>{busy?"Removing…":"Confirm removal"}</button></div></form></div>}
 {backup.length>0&&<div className="modal-backdrop"><div className="panel modal"><div className="modal-head"><div><h2>Back up these keys now</h2><p className="muted" style={{fontSize:12,margin:"5px 0 0"}}>They will not be shown again after closing.</p></div></div><div className="wallet-picker" style={{maxHeight:260}}>{backup.map(w=><div className="wallet-option" key={w.address}><span>{w.label}</span><small className="mono">{short(w.address)}</small></div>)}</div><div className="alert" style={{margin:"14px 0"}}>Store the file offline. Anyone with these keys controls the wallets.</div><div className="toolbar"><button className="primary-btn" onClick={downloadBackup}>Download backup</button><button className="secondary-btn" onClick={()=>navigator.clipboard.writeText(JSON.stringify(backup,null,2))}>Copy JSON</button><button className="secondary-btn" onClick={()=>setBackup([])}>I saved it</button></div></div></div>}</>;
}
