"use client";
import { useEffect,useState } from "react";

type Wallet={id:string;label:string;address:string;chainId:number;keyFormat:string;active:boolean;role:"main"|"worker";parentWalletId:string|null};
type BackupWallet={label:string;address:string;privateKey:string};
type Chain={id:number;name:string;symbol:string};
const short=(v:string)=>`${v.slice(0,7)}…${v.slice(-5)}`;

export default function WalletsPage(){
 const [wallets,setWallets]=useState<Wallet[]>([]),[chains,setChains]=useState<Chain[]>([]),[loading,setLoading]=useState(true),[modal,setModal]=useState(false),[generateModal,setGenerateModal]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[backup,setBackup]=useState<BackupWallet[]>([]);
 const [form,setForm]=useState({label:"",chainId:1,keyType:"private-key",key:"",role:"main" as "main"|"worker",parentWalletId:""});
 const [generate,setGenerate]=useState({prefix:"Worker",chainId:1,count:10,parentWalletId:""});
 const load=()=>Promise.all([fetch("/api/wallets").then(r=>r.json()),fetch("/api/chains").then(r=>r.json())]).then(([w,c])=>{setWallets(Array.isArray(w)?w:[]);setChains(Array.isArray(c)?c:[]);setLoading(false)});
 useEffect(()=>{load()},[]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/wallets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,parentWalletId:form.role==="worker"?form.parentWalletId:undefined})});const d=await r.json();if(!r.ok)throw new Error(d.error);setModal(false);setForm({label:"",chainId:1,keyType:"private-key",key:"",role:"main",parentWalletId:""});load()}catch(e){setError(e instanceof Error?e.message:"Import failed")}finally{setBusy(false)}};
 const createWallets=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/wallets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"generate",...generate})});const d=await r.json();if(!r.ok)throw new Error(d.error);setBackup(d.wallets);setGenerateModal(false);load()}catch(e){setError(e instanceof Error?e.message:"Generation failed")}finally{setBusy(false)}};
 const mainWallets=wallets.filter(w=>w.role==="main");
 const downloadBackup=()=>{const blob=new Blob([JSON.stringify(backup,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`mintbot-wallet-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)};
 const closeImport=()=>{setModal(false);setForm(current=>({...current,key:""}))};
 const remove=async(id:string)=>{if(!confirm("Remove this wallet from MintBot?"))return;setError("");try{const response=await fetch(`/api/wallets/${id}`,{method:"DELETE"});const data=await response.json();if(!response.ok)throw new Error(data.error);await load()}catch(error){setError(error instanceof Error?error.message:"Could not remove wallet")}};
 return <><div className="page-heading"><div><h1>Wallets</h1><p>Create, import and organise the wallets used for your mints.</p></div><div className="toolbar"><button className="secondary-btn" onClick={()=>navigator.clipboard.writeText(wallets.map(w=>w.address).join("\n"))}>Copy addresses</button><button className="secondary-btn" onClick={()=>{setError("");setModal(true)}}>Import</button><button className="primary-btn" onClick={()=>{setError("");setGenerateModal(true)}}>+ Create wallets</button></div></div>
 <div className="panel table-wrap">{loading?<div className="empty"><p>Loading wallets…</p></div>:wallets.length?<table className="wallet-table"><thead><tr><th>Name</th><th>Address</th><th>Network</th><th>Role</th><th></th></tr></thead><tbody>{wallets.map(w=><tr key={w.id}><td><b>{w.role==="worker"?"↳ ":""}{w.label}</b></td><td className="mono">{short(w.address)} <button className="icon-button" style={{width:28,height:28,fontSize:12,marginLeft:6}} onClick={()=>navigator.clipboard.writeText(w.address)}>⧉</button></td><td>{chains.find(c=>c.id===w.chainId)?.name||`Chain ${w.chainId}`}</td><td className="muted">{w.role==="main"?"Main wallet":"Worker"}</td><td><button className="secondary-btn" style={{padding:"6px 9px",color:"var(--danger)"}} onClick={()=>remove(w.id)}>Remove</button></td></tr>)}</tbody></table>:<div className="empty"><div><h2>No wallets yet</h2><p>Import your main wallet first, then create workers under it.</p><button className="primary-btn" style={{marginTop:18}} onClick={()=>setModal(true)}>Import main wallet</button></div></div>}</div>
 {modal&&<div className="modal-backdrop" onMouseDown={closeImport}><form className="panel modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>Import wallet</h2><p className="muted" style={{fontSize:12,margin:"5px 0 0"}}>Keys are encrypted before storage.</p></div><button type="button" onClick={closeImport}>×</button></div>{error&&<div className="alert" style={{color:"var(--danger)",marginBottom:14}}>{error}</div>}<div className="form-grid"><div className="segmented"><button type="button" className={form.role==="main"?"active":""} onClick={()=>setForm({...form,role:"main",parentWalletId:""})}>Main wallet</button><button type="button" className={form.role==="worker"?"active":""} onClick={()=>setForm({...form,role:"worker"})}>Worker</button></div><div className="segmented"><button type="button" className={form.keyType==="private-key"?"active":""} onClick={()=>setForm({...form,keyType:"private-key"})}>Private key</button><button type="button" className={form.keyType==="mnemonic"?"active":""} onClick={()=>setForm({...form,keyType:"mnemonic"})}>Seed phrase</button></div><div className="field"><label>Wallet name</label><input required value={form.label} onChange={e=>setForm({...form,label:e.target.value})} placeholder={form.role==="main"?"Main":"Worker 01"}/></div><div className="field"><label>Network</label><select value={form.chainId} onChange={e=>setForm({...form,chainId:Number(e.target.value),parentWalletId:""})}>{chains.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>{form.role==="worker"&&<div className="field"><label>Main wallet</label><select required value={form.parentWalletId} onChange={e=>setForm({...form,parentWalletId:e.target.value})}><option value="">Choose main</option>{mainWallets.filter(w=>w.chainId===form.chainId&&w.active).map(w=><option key={w.id} value={w.id}>{w.label}</option>)}</select></div>}<div className="field"><label>{form.keyType==="mnemonic"?"Seed phrase":"Private key"}</label><textarea required rows={3} value={form.key} onChange={e=>setForm({...form,key:e.target.value})} placeholder={form.keyType==="mnemonic"?"Enter 12–24 words":"0x…"}/></div><button className="primary-btn" disabled={busy}>{busy?"Encrypting & importing…":"Import wallet"}</button></div></form></div>}
 {generateModal&&<div className="modal-backdrop" onMouseDown={()=>setGenerateModal(false)}><form className="panel modal" onSubmit={createWallets} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>Create worker wallets</h2><p className="muted" style={{fontSize:12,margin:"5px 0 0"}}>Independent keys, grouped beneath your main wallet.</p></div><button type="button" onClick={()=>setGenerateModal(false)}>×</button></div>{error&&<div className="alert" style={{color:"var(--danger)",marginBottom:14}}>{error}</div>}<div className="form-grid"><div className="field"><label>Main wallet</label><select required value={generate.parentWalletId} onChange={e=>{const main=mainWallets.find(w=>w.id===e.target.value);setGenerate({...generate,parentWalletId:e.target.value,chainId:main?.chainId||generate.chainId})}}><option value="">Choose main</option>{mainWallets.map(w=><option key={w.id} value={w.id}>{w.label}</option>)}</select></div><div className="field"><label>Name prefix</label><input required value={generate.prefix} onChange={e=>setGenerate({...generate,prefix:e.target.value})} placeholder="Worker"/></div><div className="field"><label>Count (maximum 100)</label><div className="amount-row"><input type="number" min="1" max="100" value={generate.count} onChange={e=>setGenerate({...generate,count:Math.max(1,Math.min(100,Number(e.target.value)||1))})}/><button type="button" className="secondary-btn" onClick={()=>setGenerate({...generate,count:100})}>MAX</button></div></div><div className="alert">Private keys are shown once after creation. Back them up before funding.</div><button className="primary-btn" disabled={busy||!generate.parentWalletId}>{busy?`Creating ${generate.count}…`:`Create ${generate.count} worker${generate.count===1?"":"s"}`}</button></div></form></div>}
 {backup.length>0&&<div className="modal-backdrop"><div className="panel modal"><div className="modal-head"><div><h2>Back up these keys now</h2><p className="muted" style={{fontSize:12,margin:"5px 0 0"}}>They will not be shown again after closing.</p></div></div><div className="wallet-picker" style={{maxHeight:260}}>{backup.map(w=><div className="wallet-option" key={w.address}><span>{w.label}</span><small className="mono">{short(w.address)}</small></div>)}</div><div className="alert" style={{margin:"14px 0"}}>Store the file offline. Anyone with these keys controls the wallets.</div><div className="toolbar"><button className="primary-btn" onClick={downloadBackup}>Download backup</button><button className="secondary-btn" onClick={()=>navigator.clipboard.writeText(JSON.stringify(backup,null,2))}>Copy JSON</button><button className="secondary-btn" onClick={()=>setBackup([])}>I saved it</button></div></div></div>}</>;
}
